### ISSUE TITLE
installing instapy ERROR

### ISSUE THREAD

**Issue by instamaverick** [InstaPy/instapy-quickstart#10]
clarifai 2.5.2 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.0 which is incompatible.
Installing collected packages: future, emoji, instapy-chromedriver, urllib3, idna, chardet, certifi, requests, six, protobuf, functools32, pyrsistent, attrs, jsonschema, enum34, configparser, futures, grpcio, googleapis-common-protos, clarifai, MeaningCloud-python, EasyProcess, PyVirtualDisplay, regex, PyYAML, selenium, plyer, instapy
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/_dummy_thread'
Consider using the `--user` option or check the permissions.

**Comment by timgrossmann** [comment]
https://github.com/timgrossmann/InstaPy/issues/4056#issuecomment-468115642
