### ISSUE TITLE
Installing Error on Mac 10.14.3

### ISSUE THREAD

**Issue by zacjuntan** [InstaPy/instapy-quickstart#11]
When trying to install instapy on my Mac running OS 10.14.3, I get these 2 errors:

Collecting googleapis-common-protos<2,>=1.5.0 (from clarifai>=2.4.1->instapy)
clarifai 2.5.2 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.0 which is incompatible.

&

Installing collected packages: enum34, futures, six, grpcio, idna, urllib3, certifi, chardet, requests, EasyProcess, instapy-chromedriver, emoji, functools32, pyrsistent, attrs, jsonschema, plyer, selenium, PyVirtualDisplay, future, PyYAML, regex, configparser, protobuf, MeaningCloud-python, googleapis-common-protos, clarifai, instapy
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/enum'
Consider using the `--user` option or check the permissions.

Check out the screenshot of my mac terminal showing these issues.
<img width="1278" alt="screen shot 2019-02-27 at 7 00 19 pm" src="https://user-images.githubusercontent.com/43363320/53538290-f250ee00-3ac1-11e9-8d5f-211a7fd4fab6.png">

Any advice or guidance through these errors would be greatly appreciated :) I'm new to anything coding related, and I'm trying to figure it out as I go but this has me stumped. Thank you!

**Comment by timgrossmann** [comment]
@zacjuntan Could you try to just `sudo` it?
Otherwise you have to use the `--user` option when using it.
Try to install it manually with `sudo pip install instapy --ignore-installed`

**Comment by timgrossmann** [comment]
Or even simpler, please use: https://github.com/timgrossmann/InstaPy/issues/4056#issuecomment-468115642

**Comment by zacjuntan** [comment]
@timgrossmann you are quite literally THE MAN. Thank you so much. This has been such a fascinating learning experience for someone who's completely new to dealing with code. The Sudo command worked with the ignore installed behind. 

But I'm still getting "clarifai 2.5.2 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.0 which is incompatible." Though the app seems to be working now so I'm not even sure what clarifai was supposed to do? 

I'm also not sure how to use the --user option.. but thanks once again.

**Comment by timgrossmann** [comment]
@zacjuntan Clarifai can be used to make sure that something is not in the picture, like nudity or that something gets specific comments, like forests get only comments how great forests are 😉 
You can check the documentation in the main repo for that 👍 

Haha, love to hear from people who got their hands dirty by dealing with code 🙌 
If you go everything working, then actually **you** are the man 😉

**Comment by timgrossmann** [comment]
If you should want to use clarifai and encounter any error, you can still uninstall jsonschema and install a specific version, but that is not too interesting for now 😉

**Comment by zacjuntan** [comment]
@timgrossmann actually that is still really interesting to me! I'll give it a shot tomorrow haha my eyes are too blurry right now. 

I got mostly everything working! The only thing would be the Clarifai, so I assume if I wrote some instructions to do a specific action based on what is in a picture in the quickstart.py, it would fail to do so/give me an error until I fixed my Clarifai error?

This is so fascinating, and thank you so much for being so helpful and responsive to a newbie, I really appreciate the help.

**Comment by timgrossmann** [comment]
@zacjuntan You should try it out, out of the box I can't tell what will happen regarding that error, sorry 😉 
If you should have problems with clarifai, simply install an older version of jsonschema

**Comment by zacjuntan** [comment]
@timgrossmann I was looking at some of the post session reports, and it seems like the app can already pickup "offensive" images as it logs the number found! So it all seems to work as intended now despite the error. If any problems come up I'll try an older version of jsonschema.
