### ISSUE TITLE
clarifai 2.6.1 has requirement jsonschema<3,>=2.5

### ISSUE THREAD

**Issue by lepri13** [InstaPy/instapy-quickstart#13]
Technical Help

Linux (Ubuntu 18.04)

Python 3.6.7

Include here the response of 'pip --version' or 'pip3 --version'
pip 19.0.3 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)

Description of your issue

Repo steps:
Install default 18.04 Ubuntu from digital ocean
git clone https://github.com/InstaPy/instapy-quickstart.git
cd instapy-quickstart/installation/Linux/
sh install.sh
most of the install runs fine I get:
clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.
press any key to complete install

Looking around there isnt any clear ways around it.

Config

Not applicable

**Comment by EdivaldoJuniorDev** [comment]
same issue here, I already try everything but until now no success please help us. I was following ur tutorial from udemy course, but this error occurs and I cant go on.

**Comment by da1z** [comment]
try
pip uninstall jsonschema

**Comment by chukwudalu01** [comment]
technical problem with installation of instapy

ERROR: clarifai 2.6.2 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.2 which is incompatible.

**Comment by Pangolino2a** [comment]
Hi !!!!! well for all call must be used PIP3 !!! for all folder and it work !!!
