### ISSUE TITLE
Cookie file not found, creating cookie...   WRONG LOGIN DATA!!! session end

### ISSUE THREAD

**Issue by davanderlinden** [InstaPy/instapy-quickstart#16]
im using an ubuntu linux server and when the cookies file is not found it says "creating cookies"
the the next line ends the session with "wrong login data".  
I dont know what this means because the login info is right.

**Comment by timgrossmann** [comment]
@davanderlinden It's suspicious about your login. You have to tell it that "this was me" in a local session of Instagram in the browser.
Use the suspicious login feature of InstaPy, please :blush:
