### ISSUE TITLE
 Doesn't see Chrome

### ISSUE THREAD

**Issue by bot08** [InstaPy/instapy-quickstart#201]
https://i.ibb.co/QnXZxQZ/2020-11-13-122820.png
Thanks in advance for your reply

**Comment by aurel2222** [comment]
> 
> 
> https://i.ibb.co/QnXZxQZ/2020-11-13-122820.png
> Thanks in advance for your reply

where did you download the version you are using ? could you copy/past the link ? I'll try to see if i have the same issue.
