### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by hulaford** [InstaPy/instapy-quickstart#21]
Had two error messages when attempting to install InstaPy:

clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/enum'
Consider using the `--user` option or check the permissions.

**Comment by igorbiagi** [comment]
Same issue to me. Did you solve it?

**Comment by hulaford** [comment]
No, not yet.

**Comment by bob4081** [comment]
I'm getting same problem also

**Comment by timgrossmann** [comment]
Please try to use the terminal and the manual instructions in the main repository.
Sorry for the inconveniences.

For further help, reference the Discord server linked in the README at InstaPy, pelase.
