### ISSUE TITLE
miss sendMessage in telegram api 

### ISSUE THREAD

**Issue by blackout314** [InstaPy/instapy-quickstart#22]
https://github.com/InstaPy/instapy-quickstart/blob/be3a73ae34d987fb98c156106ff00ce1eddfcf4f/quickstart_templates/follow_unfollow_and_send_telegram_msg.py#L39

**Comment by timgrossmann** [comment]
@blackout314 Sorry for the inconveniences... Maybe @Mehran can help you, he wrote the script 😊

**Comment by blackout314** [comment]
@timgrossmann i can fix it
