### ISSUE TITLE
Anyoneknows that is wrong?

### ISSUE THREAD

**Issue by diogoribeirodev** [InstaPy/instapy-quickstart#230]
Workspace in use: "C:/Users/ribei/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-05-02 17:58:01] [dogs.cats.lover]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-05-02 17:58:01] [dogs.cats.lover]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-05-02 17:58:02] [dogs.cats.lover]  - Internet Connection Status: ok
INFO [2021-05-02 17:58:02] [dogs.cats.lover]  - Current IP is "" and it's from ""
INFO [2021-05-02 17:58:02] [dogs.cats.lover]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-05-02 17:58:02] [dogs.cats.lover]  - window.navigator.webdriver response: True
WARNING [2021-05-02 17:58:02] [dogs.cats.lover]  - Hide Selenium Extension: error
INFO [2021-05-02 17:58:07] [dogs.cats.lover]  - Cookie file not found, creating cookie...
INFO [2021-05-02 17:58:46] [dogs.cats.lover]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\ribei\AppData\Local\Temp\20210502-175851.html
**********************************************************************

INFO [2021-05-02 17:58:52] [dogs.cats.lover]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 1.03 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-05-02 17:58:52] [dogs.cats.lover]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "C:\Users\ribei\OneDrive\Ambiente de Trabalho\InstaBot\instabot.py", line 27, in <module>
    with smart_run(session):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 119, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

**Comment by conradios** [comment]
idk but u leaked ur ip
