### ISSUE TITLE
InstaPy is unable to create cookie file?

### ISSUE THREAD

**Issue by diogoribeirodev** [InstaPy/instapy-quickstart#234]
When opening firefox, a cookie pop-ups and i don't think he is able to interact with it

INFO [2021-06-14 13:36:13] [username]  - Cookie file not found, creating cookie...
INFO [2021-06-14 13:36:53] [username]  Timed out with failure while explicitly waiting until visibility of element located!

**Comment by tobyhogan** [comment]
> When opening firefox, a cookie pop-ups and i don't think he is able to interact with it
> 
> INFO [2021-06-14 13:36:13] [username] - Cookie file not found, creating cookie... INFO [2021-06-14 13:36:53] [username] Timed out with failure while explicitly waiting until visibility of element located!

How did you solve this?
