### ISSUE TITLE
Unable to like?

### ISSUE THREAD

**Issue by diogoribeirodev** [InstaPy/instapy-quickstart#235]
After getting the post when is time to click the like button the app stops

Traceback (most recent call last):
  File "C:\Users\ribei\Downloads\Reddit\insta.py", line 32, in <module>
    session.like_by_tags(["cats"], amount=10)
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
[Finished in 207.3s]

**Comment by navjotsherry** [comment]
Same here

**Comment by navjotsherry** [comment]
`pip install -I https://github.com/schealex/InstaPy/zipball/develop`
just install it using pip or pip3

**Comment by navjotsherry** [comment]
> After getting the post when is time to click the like button the app stops
> 
> Traceback (most recent call last):
> File "C:\Users\ribei\Downloads\Reddit\insta.py", line 32, in
> session.like_by_tags(["cats"], amount=10)
> File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
> inappropriate, user_name, is_video, reason, scope = check_link(
> File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
> media = post_page[0]["shortcode_media"]
> KeyError: 0
> [Finished in 207.3s]

`pip install -I https://github.com/schealex/InstaPy/zipball/develop`
install it using pip or pip3
