### ISSUE TITLE
Internet Connection Status: error instapy

### ISSUE THREAD

**Issue by tooxiic49** [InstaPy/instapy-quickstart#260]
Hello, I have a problem. It became impossible for me to launch instapy overnight, I don't understand, is it possible to get help?

`INFO [2022-04-26 01:05:14] [***]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-04-26 01:05:14] [***]  -- Connection Checklist [1/2] (Internet Connection Status)
WARNING [2022-04-26 01:05:15] [***]  - Internet Connection Status: error
........................................................................................................................
CRITICAL [2022-04-26 01:05:15] [***]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2022-04-26 01:05:16] [***]  Sessional Live Report:
	|> No any statistics to show`

**Comment by paul-bonnel-fr** [comment]
Hey Mate ! Did you find a solution ? I have the same issue

**Comment by tooxiic49** [comment]
> 

look: [https://github.com/InstaPy/InstaPy/issues/6592](url)

**Comment by MrDzenix** [comment]
the link is expired can u send anotherone myb?

**Comment by rdxshubham** [comment]
You just need to add `want_check_browser=False` after `headless_browser=False`. Before running the script it checks if Instagram is up or not and it seems that is broken.
