### ISSUE TITLE
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (...\.venv\lib\site-packages\emoji\unicode_codes\__init__.py)

### ISSUE THREAD

**Issue by AmineMahdioui** [InstaPy/instapy-quickstart#289]
i just installed it and tried to run the quickstart and got this error
`
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (c:\Users\amine\Downloads\DataScienceNotebooks master\.venv\lib\site-packages\emoji\unicode_codes\__init__.py)`

**Comment by pietrovitagliano** [comment]
Run these commands in the prompt (I'm using Windows commands):
- pip uninstall emoji
- pip install emoji==1.7

This should resolve the problem with emojii

**Comment by AmineMahdioui** [comment]
thank you it did work but i got a different package missing now 
`ModuleNotFoundError: No module named 'clarifai.rest'`

**Comment by AmineMahdioui** [comment]
I found fix in other issues

pip uninstall clarifai
pip install clarifai==2.6.2

_Originally posted by @Raidtron in https://github.com/InstaPy/instapy-quickstart/issues/282#issuecomment-1585675841_
