### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Greene951** [InstaPy/instapy-quickstart#29]
Help would be very much appreaciated. I am following the Udemy course and received this error when installing InstaPY. Note - not extremely experienced in development.

I am receiving the attached errors. 

<img width="753" alt="Screenshot 2019-05-04 at 15 29 29" src="https://user-images.githubusercontent.com/50270958/57181385-dfc0af80-6e8a-11e9-8c7d-fb23c92532d9.png">

**Comment by timgrossmann** [comment]
@Greene951 If you encounter any `disutil` problems, "simply" install on top of them using the --ignore-installed flag.
> Note that this requires you to execute the installation command manually.

Type
`pip install instapy --ignore-installed`
into your terminal
