### ISSUE TITLE
ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible. ERROR: clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

### ISSUE THREAD

**Issue by aaronwi** [InstaPy/instapy-quickstart#30]
ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible. ERROR: clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

I'm sure this can be fixed with a virtualenv, but I did a quick and dirty hack

pip uninstall urllib3
pip uninstall jsonschema
pip install urllib3==1.24.1
pip install jsonschema==2.6.0

**Comment by marcosgb** [comment]
same here

**Comment by timgrossmann** [comment]
@aaronwi Please reopen this issue at the InstaPy main repo since this is non related to the quickstart files.
Thank you 😊
