### ISSUE TITLE
Installing Error Mac 10.13.6

### ISSUE THREAD

**Issue by ionevan** [InstaPy/instapy-quickstart#39]
Having trouble installing instapy and receive the following error messages:

**ERROR: clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.**
Installing collected packages: urllib3, certifi, chardet, idna, requests, MeaningCloud-python, six, protobuf, configparser, enum34, attrs, functools32, pyrsistent, jsonschema, googleapis-common-protos, typing, future, futures, grpcio, clarifai, EasyProcess, PyVirtualDisplay, instapy-chromedriver, emoji, plyer, selenium, PyYAML, regex, instapy
**ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/urllib3-1.25.3.dist-info'
Consider using the `--user` option or check the permissions.**

I'm new to coding so any help trying to resolve this in simple terms would be appreciated! :)

**Comment by ionevan** [comment]
UPDATE: Resolved using the terminal code _sudo pip install instapy --ignore-installed_

**Comment by beld159** [comment]
I have the same error. where do you put that code to fix it?

**Comment by ionevan** [comment]
open your terminal command and enter: sudo pip install instapy --ignore-installed
You'll then be prompted to enter your Mac pw, after which it'll start installing. 
Hope this helps!
