### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/urllib3-1.25.3.dist-info' Consider using the `--user` option or check the permissions.

### ISSUE THREAD

**Issue by isabell89** [InstaPy/instapy-quickstart#41]

**Comment by isabell89** [comment]
I'm facing with 2 errors while installing. via mac. Please help.

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/urllib3-1.25.3.dist-info'
Consider using the `--user` option or check the permissions.

ERROR: clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

**Comment by hollossy** [comment]
> ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/urllib3-1.25.3.dist-info'
> Consider using the `--user` option or check the permissions.

Hey! Are you installing it on your Mac or on a VPS? Do you have root access? 


> ERROR: clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

Try the following after the installation is complete: pip install jsonschema==2.6.0
Don't reinstall, just run the bot and it should work.

**Comment by timgrossmann** [comment]
@hollossy Thank you for the support.

@isabell89 Please either install for your user using `--user` or install globally using `sudo`.

Thank you

**Comment by samyearsley** [comment]
Hi @timgrossmann could you provide some more guidance on what you mean by 'install for your user using --user?' Thank you!
