### ISSUE TITLE
good commenting strategy and new qs system script

### ISSUE THREAD

**Issue by eFeRaven** [InstaPy/instapy-quickstart#60]
Like what this is intended to do!  I had it running great for about 30mins then started to get some follow and like errors where it wouldn't process.   How can I slow this down a little bit to try and avoid being temp banned?

**Comment by jouhoff** [comment]
You're asking how to reduce frequency of the profile posting scripts? 

2. if so, look for smth like this 

`set_do_comment(enabled=True, percentage=30)`

percentage is how often comments drop

**Comment by eFeRaven** [comment]
Awesome, figured it out thank you.   Now just hoping my accounts shadow ban gets lifted.
