### ISSUE TITLE
problem install.sh Ubuntu

### ISSUE THREAD

**Issue by rmalosse** [InstaPy/instapy-quickstart#7]
I try to install on my server Ubuntu just with script install.sh . 

I have this error : 

  100% |████████████████████████████████| 143kB 25.1MB/s 
Collecting grpcio>=1.16.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/51/a3/489ce6a67047263e9b0da8784b2925c4f89b688a6e33073c5bb6c4c2867f/grpcio-1.18.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting six>=1.11.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting configparser>=3.5.0 (from instapy)
  Downloading https://files.pythonhosted.org/packages/43/63/220afe02a0d302c2244309b1dce3d884a865be65c7d8148ededfc0c29c31/configparser-3.7.1-py3-none-any.whl
Collecting MeaningCloud-python>=1.1.1 (from instapy)
  Downloading https://files.pythonhosted.org/packages/28/c6/deb6c9d113f94ec99116ec4017b333660ce54344734d29f0cb98fdf32945/MeaningCloud_python-1.1.1-py2.py3-none-any.whl
Collecting PyYAML>=3.13 (from instapy)
  Using cached https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1mmh1g1l/PyYAML/
install.sh: 31: install.sh: pushd: not found
Setup is completed.

**Comment by timgrossmann** [comment]
@rmalosse Hey, please try google first 😊  
Have seen this problem before, this should help:
https://github.com/googleapis/google-cloud-python/issues/3884

**Comment by rmalosse** [comment]
@timgrossman  yes i know i already found solution of my problème. It’s Just if you Want to do an automatisation of the install with script there is little problem on your script. I don’t know if it’s necessary to correct this but lot of people Will ask this question 😊

**Comment by timgrossmann** [comment]
@rmalosse True, thank you very much.
Could you please update the caption if this issue with the specific problem about setup tools? 😊

**Comment by rmalosse** [comment]
@timgrossmann  it works i just need to do : 

pip3 install setuptools
pip3 install gcloud
