### ISSUE TITLE
Saying Chrome isn't installed (Windows 10)

### ISSUE THREAD

**Issue by itsjusttamtam** [InstaPy/instapy-quickstart#8]
![chrome issue](https://user-images.githubusercontent.com/46925345/53350574-78125380-3973-11e9-9a28-4cb13ca99259.png)
Everytime I try running the install.bat, it comes up with the error chrome not installed. 
I made sure that theres a chrome path, so typing chrome in CMD will run chrome. I have the latest version of chrome.
I made sure that the file location of chrome matches the install.bat location (C:\Program Files (x86)\Google\Chrome\Application).
I'm not sure the next step is?

**Comment by itsjusttamtam** [comment]
I edited the file again, and restarted my PC and it works now. Thank you!

**Comment by Vitruvia** [comment]
I'm having this exact same problem. I didn't really get how you fixed it. You put install.bat on the chrome folder?? Doesn't make much sense to me.
